load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module")
load("//common_drivers:amlogic_utils.bzl", "kernel_select")

ddk_module(
    name = "ci",
	srcs = glob([
		"amci.h",
		"cimcu/*.h",
		"aml_ci.*",
        "aml_pcmcia.*",
		"aml_ci_bus.*",
		"cimax/dvb_ringbuffer.*",
		"cimcu/dvb_ca_en50221_cimcu.*",
    ]),
    hdrs = [
    ],
    linux_includes = [
		"../../../../drivers/common/media_utils",
    ],
    local_defines = [
		],
    out = "ci.ko",
    kernel_build = kernel_select(),
    visibility = ["//visibility:public"],
    deps = [
		"//driver_modules/media_modules:media_clock",
		"//common_drivers/drivers/gki_tool:amlogic-gkitool",
		"//common_drivers/drivers/media/dvb-core:dvb-core",
    ],
)
