load("@kleaf//build/kernel/kleaf:kernel.bzl", "ddk_module")
load("//common_drivers:amlogic_utils.bzl", "kernel_select", "ddk_deps_select")

ddk_module(
    name = "hw_demux",
	srcs = glob([
        "**/*.h",
    ]),
    conditional_srcs = {
        "CONFIG_AMLOGIC_DVB_DMX": {
        True: [
                "aml_dvb.c",
                "aml_dmx.c",
            ],
        },
    },
    hdrs = [
    ],
    linux_includes = [
		"../../../../drivers/stream_input/amports",
		"../../../../drivers/stream_input/parser",
    ],
    local_defines = [
		"ENABLE_DEMUX_DRIVER",
		],
    out = "aml_hardware_dmx.ko",
    kernel_build = kernel_select(),
    visibility = ["//visibility:public"],
    deps = ddk_deps_select([
	"//driver_modules/media_modules:stream_input",
	"//driver_modules/media_modules:media_clock",
	"//common_drivers/drivers/media:aml_media",
	"//common_drivers/drivers/cpu_info:amlogic-cpuinfo",
        "//common_drivers/drivers/gki_tool:amlogic-gkitool",
        "//common_drivers/drivers/debug:amlogic-debug-iotrace",
        "//common_drivers/drivers/debug:amlogic-debug",
	"//common_drivers/drivers/media/dvb-core:dvb-core",
    ]),
)
